"use client";

import { useCallback } from "react";
import { SkeletonBlock, SectionError, SectionEmpty } from "@/components/shared/SectionState";
import type { ActionPlan } from "@/lib/schemas";
import { useDocumentStore } from "@/store/useStore";
import {
  AlertTriangle,
  ShieldOff,
  MessageSquare,
  ClipboardList,
  HelpCircle,
  BookOpen,
  ChevronRight,
  Copy,
  Download,
  Check,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { useState } from "react";

interface ActionPlanTabProps {
  action: ActionPlan | null;
  documentTitle: string;
  status: "idle" | "loading" | "done" | "error";
  error: string | null;
  onRetry: () => void;
}

export function ActionPlanTab({ action, documentTitle, status, error, onRetry }: ActionPlanTabProps) {
  const { checklistState, toggleChecklist } = useDocumentStore();
  const [copySuccess, setCopySuccess] = useState(false);

  if (status === "loading" || status === "idle") {
    return (
      <div className="p-6 space-y-6">
        <SkeletonBlock lines={5} />
        <SkeletonBlock lines={4} />
        <SkeletonBlock lines={6} />
      </div>
    );
  }

  if (status === "error") {
    return (
      <div className="p-6">
        <SectionError message={error || "Could not load action plan."} onRetry={onRetry} />
      </div>
    );
  }

  if (!action) return null;

  function buildMarkdown(): string {
    if (!action) return "";
    return `# Lawyer Brief — ${documentTitle}
*Generated by ClearPaper. General information only, not legal advice.*

## Red Flags
${(action.red_flags || []).map((f) => `- **${f.title}**: ${f.reason}`).join("\n")}

## Missing Protections
${(action.missing_protections || []).map((p) => `- **${p.title}**: ${p.why_it_matters}`).join("\n")}

## Questions for Your Lawyer
${(action.lawyer_questions || []).map((q, i) => `${i + 1}. ${q}`).join("\n")}

## Documents to Bring
${(action.documents_to_bring || []).map((d) => `- ${d}`).join("\n")}

## Pre-Signing Checklist
${(action.checklist || []).map((item) => `- [ ] ${item}`).join("\n")}

## Your Options
${(action.options || []).map((o) => `### ${o.title}\n${o.when_it_makes_sense}`).join("\n\n")}

---
*This brief was generated by ClearPaper (clearpaper.app). It is general information to help you prepare for a conversation with a qualified lawyer. It does not constitute legal advice.*`;
  }

  function downloadMarkdown() {
    const content = buildMarkdown();
    const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "lawyer-brief.md";
    a.click();
    URL.revokeObjectURL(url);
  }

  function downloadPDF() {
    // Open print dialog with print-optimized view
    const content = buildMarkdown()
      .replace(/\n/g, "<br>")
      .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
      .replace(/# (.*?)<br>/g, "<h1>$1</h1>")
      .replace(/## (.*?)<br>/g, "<h2>$1</h2>")
      .replace(/### (.*?)<br>/g, "<h3>$1</h3>");

    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    printWindow.document.write(`
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <title>Lawyer Brief — ${documentTitle}</title>
        <style>
          body { font-family: Georgia, serif; max-width: 700px; margin: 40px auto; color: #1C2321; line-height: 1.7; }
          h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }
          h2 { font-size: 1.1rem; margin-top: 2rem; margin-bottom: 0.5rem; border-bottom: 1px solid #eee; padding-bottom: 4px; }
          h3 { font-size: 1rem; margin-top: 1rem; }
          p, li { font-size: 0.9rem; }
          .disclaimer { font-size: 0.75rem; color: #888; border-top: 1px solid #eee; margin-top: 2rem; padding-top: 1rem; }
        </style>
      </head>
      <body>${content}<p class="disclaimer">Generated by ClearPaper. General information only, not legal advice.</p></body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  }

  async function copyBrief() {
    const content = buildMarkdown();
    await navigator.clipboard.writeText(content);
    setCopySuccess(true);
    setTimeout(() => setCopySuccess(false), 2000);
  }

  return (
    <div className="p-6 space-y-8" aria-label="Action plan">
      {/* Red flags */}
      {action.red_flags.length > 0 && (
        <section aria-labelledby="red-flags-heading">
          <div className="flex items-center gap-2 mb-4">
            <AlertTriangle size={16} strokeWidth={1.5} className="text-[var(--risk-high)]" aria-hidden="true" />
            <h2 id="red-flags-heading" className="text-base font-semibold text-[var(--ink)]" style={{ fontFamily: "var(--font-serif)" }}>
              Red Flags
            </h2>
          </div>
          <div className="space-y-2">
            {action.red_flags?.map((flag, i) => (
              <div key={i} className="flex items-start gap-3 p-4 rounded-[var(--radius-card)] bg-[var(--risk-high-bg)] border border-[var(--risk-high)] border-opacity-20">
                <ChevronRight size={14} strokeWidth={2} className="text-[var(--risk-high)] mt-0.5 flex-shrink-0" aria-hidden="true" />
                <div>
                  <p className="text-sm font-semibold text-[var(--risk-high)]">{flag.title}</p>
                  <p className="text-sm text-[var(--ink-muted)] mt-0.5">{flag.reason}</p>
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Missing protections */}
      {action.missing_protections.length > 0 && (
        <section aria-labelledby="missing-heading">
          <div className="flex items-center gap-2 mb-4">
            <ShieldOff size={16} strokeWidth={1.5} className="text-[var(--risk-medium)]" aria-hidden="true" />
            <h2 id="missing-heading" className="text-base font-semibold text-[var(--ink)]" style={{ fontFamily: "var(--font-serif)" }}>
              Missing Protections
            </h2>
          </div>
          <div className="space-y-2">
            {action.missing_protections?.map((p, i) => (
              <div key={i} className="p-4 rounded-[var(--radius-card)] bg-[var(--risk-medium-bg)] border border-[var(--border)]">
                <p className="text-sm font-semibold text-[var(--risk-medium)]">{p.title}</p>
                <p className="text-xs text-[var(--ink-faint)] mt-0.5 italic">Not found in this document</p>
                <p className="text-sm text-[var(--ink-muted)] mt-1">{p.why_it_matters}</p>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Negotiation points */}
      {action.negotiation_points.length > 0 && (
        <section aria-labelledby="negotiation-heading">
          <div className="flex items-center gap-2 mb-4">
            <MessageSquare size={16} strokeWidth={1.5} className="text-[var(--primary)]" aria-hidden="true" />
            <h2 id="negotiation-heading" className="text-base font-semibold text-[var(--ink)]" style={{ fontFamily: "var(--font-serif)" }}>
              Negotiation Points
            </h2>
          </div>
          <div className="space-y-4">
            {action.negotiation_points?.map((point, i) => (
              <div key={i} className="border border-[var(--border)] rounded-[var(--radius-card)] p-4 space-y-3">
                <p className="text-sm font-medium text-[var(--ink)]">{point.ask}</p>
                {point.sample_wording && (
                  <div className="bg-[var(--surface-muted)] rounded-lg p-3">
                    <p className="text-xs font-semibold text-[var(--ink-faint)] uppercase tracking-wide mb-1">Sample wording</p>
                    <p className="text-sm text-[var(--ink-muted)] italic leading-relaxed">"{point.sample_wording}"</p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Checklist */}
      {action.checklist.length > 0 && (
        <section aria-labelledby="checklist-heading">
          <div className="flex items-center gap-2 mb-4">
            <ClipboardList size={16} strokeWidth={1.5} className="text-[var(--primary)]" aria-hidden="true" />
            <h2 id="checklist-heading" className="text-base font-semibold text-[var(--ink)]" style={{ fontFamily: "var(--font-serif)" }}>
              Pre-Signing Checklist
            </h2>
          </div>
          <ul className="space-y-2" role="list">
            {action.checklist?.map((item, i) => {
              const checked = !!checklistState[item];
              return (
                <li key={i}>
                  <button
                    onClick={() => toggleChecklist(item)}
                    className={cn(
                      "w-full flex items-start gap-3 p-3 rounded-lg text-left transition-colors",
                      checked
                        ? "bg-[var(--risk-low-bg)] text-[var(--ink-faint)]"
                        : "bg-[var(--surface)] border border-[var(--border)] hover:border-[var(--primary)] hover:bg-[var(--primary-soft)]"
                    )}
                    role="checkbox"
                    aria-checked={checked}
                    aria-label={item}
                  >
                    <span
                      className={cn(
                        "flex-shrink-0 w-4 h-4 rounded border-2 flex items-center justify-center mt-0.5",
                        checked
                          ? "bg-[var(--risk-low)] border-[var(--risk-low)]"
                          : "border-[var(--border-strong)]"
                      )}
                      aria-hidden="true"
                    >
                      {checked && <Check size={10} strokeWidth={3} className="text-white" />}
                    </span>
                    <span className={cn("text-sm", checked && "line-through")}>{item}</span>
                  </button>
                </li>
              );
            })}
          </ul>
        </section>
      )}

      {/* Lawyer brief */}
      <section aria-labelledby="lawyer-brief-heading" className="border border-[var(--border)] rounded-[var(--radius-card)] p-5">
        <div className="flex items-center gap-2 mb-4">
          <BookOpen size={16} strokeWidth={1.5} className="text-[var(--primary)]" aria-hidden="true" />
          <h2 id="lawyer-brief-heading" className="text-base font-semibold text-[var(--ink)]" style={{ fontFamily: "var(--font-serif)" }}>
            Prepare for Your Lawyer
          </h2>
        </div>

        <div className="space-y-4 mb-6">
          {action.lawyer_questions.length > 0 && (
            <div>
              <p className="text-xs font-semibold text-[var(--ink-faint)] uppercase tracking-wide mb-2">
                Questions to ask
              </p>
              <ol className="space-y-1">
                {action.lawyer_questions?.map((q, i) => (
                  <li key={i} className="text-sm text-[var(--ink-muted)] flex items-start gap-2">
                    <span className="text-[var(--ink-faint)] tabular-nums mt-0.5 flex-shrink-0">{i + 1}.</span>
                    {q}
                  </li>
                ))}
              </ol>
            </div>
          )}

          {action.documents_to_bring.length > 0 && (
            <div>
              <p className="text-xs font-semibold text-[var(--ink-faint)] uppercase tracking-wide mb-2">
                Documents to bring
              </p>
              <ul className="space-y-1">
                {action.documents_to_bring?.map((d, i) => (
                  <li key={i} className="text-sm text-[var(--ink-muted)] flex items-center gap-2">
                    <ChevronRight size={12} className="text-[var(--ink-faint)] flex-shrink-0" aria-hidden="true" />
                    {d}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>

        <div className="flex flex-wrap gap-2">
          <button
            onClick={copyBrief}
            className="flex items-center gap-1.5 px-3 py-2 text-sm font-medium rounded-lg border border-[var(--border)] text-[var(--ink-muted)] hover:border-[var(--primary)] hover:text-[var(--primary)] hover:bg-[var(--primary-soft)] transition-colors"
            aria-label="Copy lawyer brief to clipboard"
          >
            {copySuccess ? (
              <><Check size={14} strokeWidth={1.5} aria-hidden="true" /> Copied!</>
            ) : (
              <><Copy size={14} strokeWidth={1.5} aria-hidden="true" /> Copy</>
            )}
          </button>
          <button
            onClick={downloadPDF}
            className="flex items-center gap-1.5 px-3 py-2 text-sm font-medium rounded-lg border border-[var(--border)] text-[var(--ink-muted)] hover:border-[var(--primary)] hover:text-[var(--primary)] hover:bg-[var(--primary-soft)] transition-colors"
            aria-label="Download lawyer brief as PDF"
          >
            <Download size={14} strokeWidth={1.5} aria-hidden="true" />
            Download PDF
          </button>
          <button
            onClick={downloadMarkdown}
            className="flex items-center gap-1.5 px-3 py-2 text-sm font-medium rounded-lg border border-[var(--border)] text-[var(--ink-muted)] hover:border-[var(--primary)] hover:text-[var(--primary)] hover:bg-[var(--primary-soft)] transition-colors"
            aria-label="Download lawyer brief as Markdown"
          >
            <Download size={14} strokeWidth={1.5} aria-hidden="true" />
            Download .md
          </button>
        </div>

        <p className="text-xs text-[var(--ink-faint)] mt-3">
          This brief is general information. It is not legal advice and does not create an attorney-client relationship.
        </p>
      </section>

      {/* Options */}
      {action.options.length > 0 && (
        <section aria-labelledby="options-heading">
          <div className="flex items-center gap-2 mb-4">
            <HelpCircle size={16} strokeWidth={1.5} className="text-[var(--ink-muted)]" aria-hidden="true" />
            <h2 id="options-heading" className="text-base font-semibold text-[var(--ink)]" style={{ fontFamily: "var(--font-serif)" }}>
              Your Options
            </h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {action.options?.map((option, i) => (
              <div key={i} className="p-4 rounded-[var(--radius-card)] border border-[var(--border)] bg-[var(--surface)]">
                <p className="text-sm font-semibold text-[var(--ink)] mb-1">{option.title}</p>
                <p className="text-xs text-[var(--ink-muted)] leading-relaxed">{option.when_it_makes_sense}</p>
              </div>
            ))}
          </div>
        </section>
      )}
    </div>
  );
}
